## Generate CRL
gen-crl --ca rootca1 --outform $OUTFORM --out output/rootca1-camgmt-gen.crl

gen-crl --ca subcawithcrl1 --outform $OUTFORM \
  --out output/subcawithcrl1-camgmt-gen.crl

gen-crl --ca subca1 --outform $OUTFORM --out output/subca1-camgmt-gen.crl

## Get CRL
get-crl --ca rootca1 --outform $OUTFORM --out output/rootca1-camgmt-get.crl

get-crl --ca subcawithcrl1 --outform $OUTFORM \
  --out output/subcawithcrl1-camgmt-get.crl

csr-p12 REPLACEME-RSAPSS --p12 output/cross1.p12 --password CHANGEIT \
  --subject "CN=cross1,O=myorg,C=DE" --outform $OUTFORM \
  --out output/cross1.csr

enroll-cert --ca rootca1 --profile cross --csr output/cross1.csr \
  --outform $OUTFORM --out output/cross1.crt

echo "#################################################################"
echo "#                Manage certificate over CMP                    #"
echo "#################################################################"

set SIGNER_P12 xipki/keycerts/cmp-client.p12

## Enroll certificates
# Certificate ocsp1

## Create the CSR for the command caqa:check-cert in QA
csr-p12 REPLACEME-RSAPSS --p12 output/ocsp1.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/ocsp1.csr \
  --subject "CN=ocsp1,2.5.4.97=VATDE-123456789,O=myorg,C=DE"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subcawithcrl --profile OCSP \
  --p12 output/ocsp1.p12 --password CHANGEIT --outform $OUTFORM \
  --out output/ocsp1.crt \
  --subject "CN=ocsp1,2.5.4.97=VATDE-123456789,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ocsp1.p12 --password CHANGEIT \
  --cert output/ocsp1.crt --ca-cert output/subcawithcrl1.crt \
  --ca-cert output/rootca1.crt

# Certificate ocsp2

## Create the CSR for the command caqa:check-cert in QA
csr-p12 REPLACEME-RSAPSS --p12 output/ocsp2.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/ocsp2.csr \
  --subject "CN=ocsp2,2.5.4.97=VATDE-123456789,O=myorg,C=DE"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subcawithcrl --profile OCSP \
  --p12 output/ocsp2.p12 --password CHANGEIT --outform $OUTFORM \
  --out output/ocsp2.crt \
  --subject "CN=ocsp2,2.5.4.97=VATDE-123456789,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ocsp2.p12 --password CHANGEIT \
  --cert output/ocsp2.crt --ca-cert output/subcawithcrl1.crt \
  --ca-cert output/rootca1.crt

# CMP update
cmp-update-p12 --ca subcawithcrl --p12 output/ocsp2.p12 --password CHANGEIT \
  --out output/ocsp2-updated.crt --oldcert output/ocsp2.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

# CMP: Enroll (CA generate key pair) via CRMF
set CN cmp-crmf-ca-genkey-tls

cmp-enroll-serverkeygen --ca subca --profile tls --p12-out output/${CN}.p12 \
  --password CHANGEIT --cert-outform $OUTFORM --cert-out output/${CN}.crt \
  --subject "CN=${CN}.myorg.org,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

source qa/qa.d/ra-serverkeygen.script

## Revocate certificates
cmp-revoke --ca subcawithcrl --ca-cert output/subcawithcrl1.crt \
  --cert output/ocsp2.crt --reason keyCompromise \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

# Certificate multiple-ous

## Create the CSR for the command caqa:check-cert in QA
csr-p12 REPLACEME-RSAPSS --p12 output/multiple-ous1.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/multiple-ous1.csr \
  --subject "CN=multiple-ous1,OU=A12345,OU=54321,O=myorg,C=DE"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subcawithcrl --profile multiple-ous \
  --p12 output/multiple-ous1.p12 --password CHANGEIT --outform $OUTFORM \
  --out output/multiple-ous1.crt \
  --subject "CN=multiple-ous1,OU=A12345,OU=54321,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/multiple-ous1.p12 --password CHANGEIT \
  --cert output/multiple-ous1.crt --ca-cert output/subcawithcrl1.crt \
  --ca-cert output/rootca1.crt

## Create the CSR for the command caqa:check-cert in QA
csr-p12 REPLACEME-RSAPSS --p12 output/multiple-ous2.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/multiple-ous2.csr \
  --subject "CN=multiple-ous2,OU=54321,OU=A12345,O=myorg,C=DE"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subcawithcrl --profile multiple-ous \
  --p12 output/multiple-ous2.p12 --password CHANGEIT --outform $OUTFORM \
  --out output/multiple-ous2.crt \
  --subject "CN=multiple-ous2,OU=54321,OU=A12345,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/multiple-ous2.p12 --password CHANGEIT \
  --cert output/multiple-ous2.crt --ca-cert output/subcawithcrl1.crt \
  --ca-cert output/rootca1.crt

# Certificate qc

csr-p12 REPLACEME-RSAPSS --p12 output/qc1.p12 --password CHANGEIT \
  --out output/qc1.csr \
  --subject "CN=qc1,2.5.4.97=VATDE-123456789,O=myorg,C=DE"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subca --profile qc --p12 output/qc1.p12 \
  --password CHANGEIT --outform $OUTFORM --out output/qc1.crt \
  --subject "CN=qc1,2.5.4.97=VATDE-123456789,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/qc1.p12 --password CHANGEIT --cert output/qc1.crt \
  --ca-cert output/subcawithcrl1.crt --ca-cert output/rootca1.crt

# Certificate fixed-partial-subject1

csr-p12 REPLACEME-RSAPSS --p12 output/fixed-partial-subject1.p12 \
  --password CHANGEIT --out output/fixed-partial-subject1.csr \
  --subject "CN=fixed-partial-subject1"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subca --profile fixed-partial-subject \
  --p12 output/fixed-partial-subject1.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/fixed-partial-subject1.crt \
  --subject "CN=fixed-partial-subject1" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/fixed-partial-subject1.p12 --password CHANGEIT \
  --cert output/fixed-partial-subject1.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate fixed-partial-subject2

csr-p12 REPLACEME-RSAPSS --p12 output/fixed-partial-subject2.p12 \
  --password CHANGEIT --out output/fixed-partial-subject2.csr \
  --subject "CN=fixed-partial-subject2"

cmp-enroll-p12 REPLACEME-RSAPSS --ca subca --profile fixed-partial-subject \
  --p12 output/fixed-partial-subject2.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/fixed-partial-subject2.crt \
  --subject "CN=fixed-partial-subject2" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/fixed-partial-subject2.p12 --password CHANGEIT \
  --cert output/fixed-partial-subject2.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate ee-complex1 with complex subject (parsable in openssl)

csr-p12 REPLACEME-RSAPSS --p12 output/ee-complex1.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/ee-complex1.csr \
  --subject \
  "UID=abc-def,CN=ee-complex1,O=myorg,C=DE,1.3.6.1.4.1.311.60.2.1.3=CN,1.3.6.1.4.1.311.60.2.1.2=Guandong,1.3.6.1.4.1.311.60.2.1.1=Shenzhen" \
  --san '[0]1.2.3.1=SAN-I am otherName 1.2.3.1' \
  --san '[0]1.2.3.2=SAN-I am otherName 1.2.3.2' \
  --san '[1]SNA-info@myorg.org' \
  --san '[2]SAN-dns.myorg.org' \
  --san '[4]CN=demo,C=DE' \
  --san '[5]SAN-assigner1=SAN-party1' \
  --san '[6]SAN-uri.myorg.org' \
  --san '[7]69.1.2.190' \
  --san '[8]2.3.4.5' \
  --sia '1.3.6.1.5.5.7.48.5=[0]1.2.3.1\=SIA-I am otherName 1.2.3.1' \
  --sia '2.3.4.1=[0]1.2.3.2\=SIA-I am otherName 1.2.3.2' \
  --sia '2.3.4.2=[1]SNA-info@myorg.org' --sia '2.3.4.3=[2]SIA-dns.myorg.org' \
  --sia '2.3.4.4=[4]CN\=demo\,C\=DE' \
  --sia '2.3.4.5=[5]SIA-assigner1\=SIA-party1' \
  --sia '2.3.4.6=[6]SIA-uri.myorg.org' --sia '2.3.4.7=[7]69.1.2.190' \
  --sia '2.3.4.8=[8]2.3.4.5' \
  --extensions-file qa/extensions/ee-complex.der

cmp-csr-enroll --csr output/ee-complex1.csr --ca subca --profile ee-complex \
  --outform $OUTFORM --out output/ee-complex1.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ee-complex1.p12 --password CHANGEIT \
  --cert output/ee-complex1.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate ee-complex2 with complex subject (not parsable in openssl due to \
  complex subject)

csr-p12 REPLACEME-RSAPSS --p12 output/ee-complex2.p12 --password CHANGEIT \
  --outform $OUTFORM --out output/ee-complex2.csr \
  --subject \
  "UID=abc-def,CN=ee-complex2,O=myorg,C=DE,1.3.6.1.4.1.311.60.2.1.3=CN,1.3.6.1.4.1.311.60.2.1.2=Guandong,1.3.6.1.4.1.311.60.2.1.1=Shenzhen" \
  --san '[0]1.2.3.1=SAN-I am otherName 1.2.3.1' \
  --san '[0]1.2.3.2=SAN-I am otherName 1.2.3.2' \
  --san '[1]SNA-info@myorg.org' \
  --san '[2]SAN-dns.myorg.org' \
  --san '[4]CN=demo,C=DE' \
  --san '[5]SAN-assigner1=SAN-party1' \
  --san '[6]SAN-uri.myorg.org' \
  --san '[7]69.1.2.190' --san '[8]2.3.4.5' \
  --sia '1.3.6.1.5.5.7.48.5=[0]1.2.3.1\=SIA-I am otherName 1.2.3.1' \
  --sia '2.3.4.1=[0]1.2.3.2\=SIA-I am otherName 1.2.3.2' \
  --sia '2.3.4.2=[1]SNA-info@myorg.org' --sia '2.3.4.3=[2]SIA-dns.myorg.org' \
  --sia '2.3.4.4=[4]CN\=demo\,C\=DE' \
  --sia '2.3.4.5=[5]SIA-assigner1\=SIA-party1' \
  --sia '2.3.4.6=[6]SIA-uri.myorg.org' --sia '2.3.4.7=[7]69.1.2.190' \
  --sia '2.3.4.8=[8]2.3.4.5' \
  --extensions-file qa/extensions/ee-complex.der

cmp-csr-enroll --csr output/ee-complex2.csr --ca subca --profile ee-complex \
  --outform $OUTFORM --out output/ee-complex2.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ee-complex2.p12 --password CHANGEIT \
  --cert output/ee-complex2.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificates constant-ext1

set list [ constant-ext ]

for it in $list
  set certname $it

  csr-p12 REPLACEME-RSAPSS --subject "CN=${certname}1,O=myorg,C=DE" \
    --p12 output/${certname}1.p12 --password CHANGEIT --outform $OUTFORM \
    --out output/${certname}1.csr

  cmp-csr-enroll --csr output/${certname}1.csr --ca subca \
    --profile ${certname} --outform $OUTFORM --out output/${certname}1.crt \
    --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

  update-cert-p12 --p12 output/${certname}1.p12 --password CHANGEIT \
    --cert output/${certname}1.crt --ca-cert output/subca1.crt \
    --ca-cert output/rootca1.crt
done

# Certificate smime1

csr-p12 REPLACEME-RSAPSS --p12 output/smime1.p12 --password CHANGEIT \
  --subject "CN=smime1,E=InFo@myorg.com,O=myorg,C=DE" --outform $OUTFORM \
  --out output/smime1.csr
cmp-csr-enroll --csr output/smime1.csr --ca subca --profile smime \
  --outform $OUTFORM --out output/smime1.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/smime1.p12 --password CHANGEIT \
  --cert output/smime1.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate smime-alias

set CN smime-alias

cmp-enroll-serverkeygen --ca subca --profile smime-alias \
  --p12-out output/${CN}.p12 --password CHANGEIT --cert-outform $OUTFORM \
  --cert-out output/${CN}.crt \
  --subject "CN={CN},E=InFo@myorg.com,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

# Certificate smime-legacy1

csr-p12 REPLACEME-RSAPSS --p12 output/smime-legacy1.p12 --password CHANGEIT \
  --subject "CN=smime-legacy1,E=InFo@myorg.com,O=myorg,C=DE" \
  --outform $OUTFORM --out output/smime-legacy1.csr
cmp-csr-enroll --csr output/smime-legacy1.csr --ca subca \
  --profile smime-legacy --outform $OUTFORM --out output/smime-legacy1.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/smime-legacy1.p12 --password CHANGEIT \
  --cert output/smime-legacy1.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate tls1

csr-p12 REPLACEME-RSAPSS --p12 output/tls1.p12 --password CHANGEIT \
  --subject "CN=tls1.myorg.org,O=myorg,C=DE" --outform $OUTFORM \
  --out output/tls1.csr
cmp-csr-enroll --csr output/tls1.csr --ca subca --profile tls \
  --outform $OUTFORM --out output/tls1.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/tls1.p12 --password CHANGEIT \
  --cert output/tls1.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate tls2

csr-p12 REPLACEME-RSAPSS --p12 output/tls2.p12 --password CHANGEIT \
  --subject "CN=tls2.myorg.org,O=myorg,C=DE" --outform $OUTFORM \
  --out output/tls2.csr

cmp-csr-enroll --csr output/tls2.csr --ca subca --profile tls \
  --outform $OUTFORM --out output/tls2.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/tls2.p12 --password CHANGEIT \
  --cert output/tls2.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate tls-alias1

set CN tls-alias1

cmp-enroll-serverkeygen --ca subca --profile tls-alias1 \
  --p12-out output/${CN}.p12 --password CHANGEIT --cert-outform $OUTFORM \
  --cert-out output/${CN}.crt --subject "CN=${CN}.org,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

# Certificate tls-alias2

set CN tls-alias2

cmp-enroll-serverkeygen --ca subca --profile tls-alias2 \
  --p12-out output/${CN}.p12 --password CHANGEIT --cert-outform $OUTFORM \
  --cert-out output/${CN}.crt --subject "CN=${CN}.org,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

## Suspend certificates
cmp-revoke --ca subca1 --cert output/tls1.crt --cert output/tls2.crt \
  --ca-cert output/subca1.crt --reason certificateHold \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

cmp-unsuspend --ca subca1 --cert output/tls1.crt --cert output/tls2.crt \
  --ca-cert output/subca1.crt --signer-password $[cmp.client.keyPassword] \
  --signer-p12 ${SIGNER_P12}

## Revoke certificates
cmp-revoke --ca subca1 --cert output/tls2.crt --ca-cert output/subca1.crt \
  --reason affiliationChanged --signer-password $[cmp.client.keyPassword] \
  --signer-p12 ${SIGNER_P12}

## Enroll certificates

# Certificate tls-c1

csr-p12 REPLACEME-RSAPSS --p12 output/tls-c1.p12 --password CHANGEIT \
  --subject "CN=tls-c1,O=myorg,C=DE" --outform $OUTFORM \
  --out output/tls-c1.csr

cmp-csr-enroll --csr output/tls-c1.csr --ca subca --profile tls-c \
  --outform $OUTFORM --out output/tls-c1.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/tls-c1.p12 --password CHANGEIT \
  --cert output/tls-c1.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate tls-c2

csr-p12 REPLACEME-RSAPSS --p12 output/tls-c2.p12 --password CHANGEIT \
  --subject "CN=tls-c2,O=myorg,C=DE" --outform $OUTFORM \
  --out output/tls-c2.csr

cmp-csr-enroll --csr output/tls-c2.csr --ca subca --profile tls-c \
  --outform $OUTFORM --out output/tls-c2.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/tls-c2.p12 --password CHANGEIT \
  --cert output/tls-c2.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

## Revocate certificates
cmp-revoke --ca subca1 --cert output/tls-c2.crt --ca-cert output/subca1.crt \
  --reason affiliationChanged --signer-password $[cmp.client.keyPassword] \
  --signer-p12 ${SIGNER_P12}

# Certificate microsoft

csr-p12 REPLACEME-RSAPSS --p12 output/microsoft.p12 --password CHANGEIT \
  --subject "CN=microsoft.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/microsoft.der \
  --outform $OUTFORM \
  --out output/microsoft.csr

cmp-csr-enroll --csr output/microsoft.csr --ca subca --profile microsoft \
  --outform $OUTFORM --out output/microsoft.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/microsoft.p12 --password CHANGEIT \
  --cert output/microsoft.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate gmt0015

csr-p12 REPLACEME-RSAPSS --p12 output/gmt0015.p12 --password CHANGEIT \
  --subject "CN=gmt0015.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/gmt0015.der \
  --outform $OUTFORM \
  --out output/gmt0015.csr

cmp-csr-enroll --csr output/gmt0015.csr --ca subca --profile gmt0015 \
  --outform $OUTFORM --out output/gmt0015.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/gmt0015.p12 --password CHANGEIT \
  --cert output/gmt0015.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate rpki

csr-p12 REPLACEME-RSAPSS --p12 output/rpki.p12 --password CHANGEIT \
  --subject "CN=rpki.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/rpki.der \
  --outform $OUTFORM \
  --out output/rpki.csr

cmp-csr-enroll --csr output/rpki.csr --ca subca --profile rpki \
  --outform $OUTFORM --out output/rpki.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/rpki.p12 --password CHANGEIT \
  --cert output/rpki.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate spdm

csr-p12 REPLACEME-RSAPSS --p12 output/spdm.p12 --password CHANGEIT \
  --subject "CN=spdm.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/spdm.der \
  --outform $OUTFORM \
  --out output/spdm.csr

cmp-csr-enroll --csr output/spdm.csr --ca subca --profile spdm \
  --outform $OUTFORM --out output/spdm.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/spdm.p12 --password CHANGEIT \
  --cert output/spdm.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate stir

csr-p12 REPLACEME-RSAPSS --p12 output/stir.p12 --password CHANGEIT \
  --subject "CN=spdm.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/stir.der \
  --outform $OUTFORM \
  --out output/stir.csr

cmp-csr-enroll --csr output/stir.csr --ca subca --profile stir \
  --outform $OUTFORM --out output/stir.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/stir.p12 --password CHANGEIT \
  --cert output/stir.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate rfc3739

csr-p12 REPLACEME-RSAPSS --p12 output/rfc3739.p12 --password CHANGEIT \
  --subject "CN=rfc3739.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/rfc3739.der \
  --outform $OUTFORM \
  --out output/rfc3739.csr

cmp-csr-enroll --csr output/rfc3739.csr --ca subca --profile rfc3739 \
  --outform $OUTFORM --out output/rfc3739.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/rfc3739.p12 --password CHANGEIT \
  --cert output/rfc3739.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate BRSKI

csr-p12 REPLACEME-RSAPSS --p12 output/brski.p12 --password CHANGEIT \
  --subject "CN=brski.myorg.org,O=myorg,C=DE" \
  --outform $OUTFORM \
  --out output/brski.csr

cmp-csr-enroll --csr output/brski.csr --ca subca --profile brski \
  --outform $OUTFORM --out output/brski.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/brski.p12 --password CHANGEIT \
  --cert output/brski.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate matter

csr-p12 REPLACEME-RSAPSS --p12 output/matter.p12 --password CHANGEIT \
  --subject "1.3.6.1.4.1.37244.1.1=1234567890ABCDEF,CN=matter.myorg.org,O=myorg,C=DE" \
  --outform $OUTFORM \
  --out output/matter.csr

cmp-csr-enroll --csr output/matter.csr --ca subca --profile matter \
  --outform $OUTFORM --out output/matter.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/matter.p12 --password CHANGEIT \
  --cert output/matter.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate mrtd

csr-p12 REPLACEME-RSAPSS --p12 output/mrtd.p12 --password CHANGEIT \
  --subject "CN=mrtd.myorg.org,O=myorg,C=DE" \
  --outform $OUTFORM \
  --out output/mrtd.csr

cmp-csr-enroll --csr output/mrtd.csr --ca subca --profile mrtd \
  --outform $OUTFORM --out output/mrtd.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/mrtd.p12 --password CHANGEIT \
  --cert output/mrtd.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate dice

csr-p12 REPLACEME-RSAPSS --p12 output/dice.p12 --password CHANGEIT \
  --subject "CN=dice.myorg.org,O=myorg,C=DE" \
  --outform $OUTFORM \
  --out output/dice.csr

cmp-csr-enroll --csr output/dice.csr --ca subca --profile dice \
  --outform $OUTFORM --out output/dice.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/dice.p12 --password CHANGEIT \
  --cert output/dice.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate tcg

csr-p12 REPLACEME-RSAPSS --p12 output/tcg.p12 --password CHANGEIT \
  --subject "CN=tcg.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/tcg.der \
  --outform $OUTFORM \
  --out output/tcg.csr

cmp-csr-enroll --csr output/tcg.csr --ca subca --profile tcg \
  --outform $OUTFORM --out output/tcg.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/tcg.p12 --password CHANGEIT \
  --cert output/tcg.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate othernames

csr-p12 REPLACEME-RSAPSS --p12 output/othernames.p12 --password CHANGEIT \
  --subject "CN=othernames.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/othernames.der \
  --outform $OUTFORM \
  --out output/othernames.csr

cmp-csr-enroll --csr output/othernames.csr --ca subca --profile othernames \
  --outform $OUTFORM --out output/othernames.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/othernames.p12 --password CHANGEIT \
  --cert output/othernames.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate caliptra

csr-p12 REPLACEME-RSAPSS --p12 output/caliptra.p12 --password CHANGEIT \
  --subject "CN=caliptra.myorg.org" \
  --extensions-file qa/extensions/caliptra.der \
  --outform $OUTFORM \
  --out output/caliptra.csr

cmp-csr-enroll --csr output/caliptra.csr --ca rootca --profile caliptra \
  --outform $OUTFORM --out output/caliptra.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/caliptra.p12 --password CHANGEIT \
  --cert output/caliptra.crt \
  --ca-cert output/rootca1.crt

# Certificate ccc-e

csr-p12 REPLACEME-RSAPSS --p12 output/ccc-e.p12 --password CHANGEIT \
  --subject "CN=ccc-e.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/ccc-e.der \
  --outform $OUTFORM \
  --out output/ccc-e.csr

cmp-csr-enroll --csr output/ccc-e.csr --ca subca --profile ccc-e \
  --outform $OUTFORM --out output/ccc-e.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ccc-e.p12 --password CHANGEIT \
  --cert output/ccc-e.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate ccc-h

csr-p12 REPLACEME-RSAPSS --p12 output/ccc-h.p12 --password CHANGEIT \
  --subject "CN=ccc-h.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/ccc-h.der \
  --outform $OUTFORM \
  --out output/ccc-h.csr

cmp-csr-enroll --csr output/ccc-h.csr --ca subca --profile ccc-h \
  --outform $OUTFORM --out output/ccc-h.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ccc-h.p12 --password CHANGEIT \
  --cert output/ccc-h.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate ccc-k

csr-p12 REPLACEME-RSAPSS --p12 output/ccc-k.p12 --password CHANGEIT \
  --subject "CN=ccc-k.myorg.org,O=myorg,C=DE" \
  --outform $OUTFORM \
  --out output/ccc-k.csr

cmp-csr-enroll --csr output/ccc-k.csr --ca subca --profile ccc-k \
  --outform $OUTFORM --out output/ccc-k.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ccc-k.p12 --password CHANGEIT \
  --cert output/ccc-k.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate ccc-t

csr-p12 REPLACEME-RSAPSS --p12 output/ccc-t.p12 --password CHANGEIT \
  --subject "CN=ccc-t.myorg.org,O=myorg,C=DE" \
  --extensions-file qa/extensions/ccc-t.der \
  --outform $OUTFORM \
  --out output/ccc-t.csr

cmp-csr-enroll --csr output/ccc-t.csr --ca subca --profile ccc-t \
  --outform $OUTFORM --out output/ccc-t.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/ccc-t.p12 --password CHANGEIT \
  --cert output/ccc-t.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate rfc9608

csr-p12 REPLACEME-RSAPSS --p12 output/rfc9608.p12 --password CHANGEIT \
  --subject "CN=rfc9608.myorg.org,O=myorg,C=DE" \
  --outform $OUTFORM \
  --out output/rfc9608.csr

cmp-csr-enroll --csr output/rfc9608.csr --ca subca --profile rfc9608 \
  --outform $OUTFORM --out output/rfc9608.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/rfc9608.p12 --password CHANGEIT \
  --cert output/rfc9608.crt --ca-cert output/subca1.crt \
  --ca-cert output/rootca1.crt

# Certificate max-time1

csr-p12 REPLACEME-RSAPSS --p12 output/max-time1.p12 --password CHANGEIT \
  --subject "CN=max-time1.myorg.org,O=myorg,C=DE" --outform $OUTFORM \
  --out output/max-time1.csr

cmp-csr-enroll --csr output/max-time1.csr --ca subcawithcrl --profile max-time \
  --outform $OUTFORM --out output/max-time1.crt \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

update-cert-p12 --p12 output/max-time1.p12 --password CHANGEIT \
  --cert output/max-time1.crt --ca-cert output/subcawithcrl1.crt \
  --ca-cert output/rootca1.crt

# Certificate for PKCS#11 key

cmp-enroll-p11 REPLACEME-RSAPSS --ca subca --profile tls --slot $SLOT \
  --key-label ${EE_P11_LABEL_PREFIX}p11-tls-cmp --outform $OUTFORM \
  --out output/p11-tls-cmp.crt \
  --subject "CN=p11-tls-cmp.example.org,O=myorg,C=DE" \
  --signer-password $[cmp.client.keyPassword] --signer-p12 ${SIGNER_P12}

## Get CRL
cmp-get-crl --ca subcawithcrl --outform $OUTFORM \
  --out output/subcawithcrl1-1-get.crl

source qa/scep.script
